import type { Exercise } from './schema';

// Deterministic IDs so seed rows can be reliably re-loaded / referenced.
// Prefix `seed-` distinguishes them from custom-exercise UUIDs.
type SeedTemplate = Omit<Exercise, 'id' | 'createdAt' | 'isCustom'> & {
  slug: string;
};

const TEMPLATES: SeedTemplate[] = [
  // ───── Brust ─────
  {
    slug: 'bankdruecken-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=vthMCtgVtFw',
    name: 'Bankdrücken Langhantel',
    category: 'compound',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders_front', 'triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    execution: {
      setup:
        'Flachbank, Schulterblätter zusammen und nach unten ziehen, Füße fest auf den Boden, leichtes Hohlkreuz, Stange über den Augen.',
      movement:
        'Stange kontrolliert zur unteren Brust senken, kurz pausieren, kraftvoll nach oben drücken bis fast durchgestreckte Ellbogen.',
      cues: [
        'Schulterblätter retrahiert halten',
        'Ellbogen ca. 45° zum Körper',
        'Stange auf Brustwarzenhöhe ablegen',
        'Atmung: einatmen ab, ausatmen drücken',
      ],
      commonMistakes: [
        'Stange auf Halshöhe absenken',
        'Ellbogen flaren über 75° (Schulter-Stress)',
        'Hintern hebt von der Bank ab',
      ],
    },
  },
  {
    slug: 'bankdruecken-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=5Y3VZsLb1Ys',
    name: 'Bankdrücken Kurzhantel',
    category: 'compound',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders_front', 'triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 150,
    execution: {
      setup: 'Flachbank, KHs auf den Oberschenkeln balancieren, mit dem Zurücklehnen nach oben kicken.',
      movement: 'KHs parallel langsam absenken bis die Ellbogen leicht unter der Bank sind, dann zusammen nach oben drücken.',
      cues: [
        'Handgelenke gerade',
        'Tiefer ROM als bei Langhantel möglich',
        'Oben kurze Spannung, keine vollständige Berührung',
      ],
      commonMistakes: ['Hanteln nach außen kippen', 'Zu schwer wählen → unsaubere Bewegung'],
    },
  },
  {
    slug: 'schraegbankdruecken-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=5kyLUGVq_pk',
    name: 'Schrägbankdrücken Langhantel',
    category: 'compound',
    primaryMuscles: ['chest', 'shoulders_front'],
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    execution: {
      setup: 'Bank auf 30-45° einstellen, Schulterblätter zusammen, Stange über den Augen.',
      movement: 'Stange zur oberen Brust senken, dann nach oben drücken.',
      cues: ['Steiler Winkel = mehr Schulter', 'Ellbogen ca. 45°', 'Volle Spannung bis ganz oben'],
      commonMistakes: ['Bank zu steil (>60°) verlagert komplett auf Schulter', 'Stange auf Schlüsselbein'],
    },
  },
  {
    slug: 'butterfly-maschine',
    videoUrl: 'https://www.youtube.com/watch?v=JYmszQs-mRs',
    name: 'Butterfly (Maschine)',
    category: 'isolation',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: 'machine',
    defaultRestSeconds: 90,
    execution: {
      setup: 'Sitz so einstellen, dass Ellbogen auf Schulterhöhe sind, Rücken fest an die Lehne.',
      movement: 'Arme aktiv zusammenführen bis die Pads sich fast berühren, kurz halten, kontrolliert zurück.',
      cues: ['Bewegung kommt aus der Brust, nicht aus den Armen', 'Volle Streckung am Endpunkt'],
      commonMistakes: ['Ellbogen zu tief', 'Mit Schwung zurückfallen lassen'],
    },
  },
  {
    slug: 'dips',
    videoUrl: 'https://www.youtube.com/watch?v=wjUmnZH528Y',
    name: 'Dips',
    category: 'compound',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders_front'],
    equipment: 'bodyweight',
    defaultRestSeconds: 150,
    execution: {
      setup: 'Schultern fixiert, Körper leicht nach vorne geneigt für mehr Brust.',
      movement: 'Bis Oberarme parallel zum Boden absenken, dann kraftvoll nach oben drücken.',
      cues: ['Schultern hinten unten', 'Ellbogen nicht ganz durchstrecken oben'],
      commonMistakes: ['Zu tief sinken → Schulterstress', 'Schwung holen'],
    },
  },
  {
    slug: 'fliegende-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=vJh-4hRLH-o',
    name: 'Fliegende mit Kurzhantel',
    category: 'isolation',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders_front'],
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
    execution: {
      setup: 'Flachbank, leichte Ellbogenbeugung halten (ca. 15°).',
      movement: 'Arme weit auseinander führen, dann mit der Brust wieder zusammenziehen.',
      cues: ['Ellbogenwinkel konstant halten', 'Bewegung im Schultergelenk, nicht im Ellbogen'],
      commonMistakes: ['Zu tief gehen → Schulter-Riss-Gefahr', 'Arme strecken (wird zur Negativbewegung)'],
    },
  },
  {
    slug: 'liegestuetze',
    videoUrl: 'https://www.youtube.com/watch?v=WDIpL0pjun0',
    name: 'Liegestütze',
    category: 'compound',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders_front', 'abs'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    execution: {
      setup: 'Hände schulterbreit, Körper gerade Linie von Kopf bis Ferse, Bauch fest.',
      movement: 'Körper kontrolliert absenken bis Brust knapp über dem Boden, dann nach oben drücken.',
      cues: ['Schulterblätter aktiv', 'Hüfte nicht durchhängen lassen'],
      commonMistakes: ['Hüfte hängt durch', 'Kopf nach unten / Hyperextension Nacken'],
    },
  },

  // ───── Rücken ─────
  {
    slug: 'klimmzug',
    videoUrl: 'https://www.youtube.com/watch?v=Hdc7Mw6BIEE',
    name: 'Klimmzug (breit, Obergriff)',
    category: 'compound',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps', 'back_rhomboids'],
    equipment: 'bodyweight',
    defaultRestSeconds: 180,
    execution: {
      setup: 'Obergriff, etwas breiter als schulterbreit, Schultern nach unten ziehen.',
      movement: 'Brust zur Stange ziehen, oben kurz halten, langsam absenken bis fast gestreckte Arme.',
      cues: ['Mit den Ellbogen ziehen, nicht mit den Bizeps-Köpfen', 'Schulterblätter zuerst aktivieren'],
      commonMistakes: ['Schwung holen (Kipping)', 'Nicht voll ausstrecken unten'],
    },
  },
  {
    slug: 'latzug-breit',
    videoUrl: 'https://www.youtube.com/watch?v=lueEJGjTuPQ',
    name: 'Latzug breit',
    category: 'compound',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps', 'back_rhomboids'],
    equipment: 'cable',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Knie unter Polster fixieren, leichtes Hohlkreuz, Stange im Obergriff fassen.',
      movement: 'Stange zur oberen Brust ziehen, Ellbogen nach unten denken, langsam zurück.',
      cues: ['Schulterblätter zuerst absenken', 'Oberkörper nur leicht nach hinten lehnen'],
      commonMistakes: ['Stange in den Nacken ziehen (Verletzungsrisiko)', 'Mit dem Rücken schwingen'],
    },
  },
  {
    slug: 'latzug-eng',
    videoUrl: 'https://www.youtube.com/watch?v=fLnD4BYg7nU',
    name: 'Latzug eng (Untergriff)',
    category: 'compound',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Schulterbreiter Untergriff, Brust raus.',
      movement: 'Stange zur Brust ziehen, Ellbogen nach unten-hinten führen.',
      cues: ['Mehr Bizeps-Beteiligung', 'Volle ROM oben'],
      commonMistakes: ['Stange zu weit hochlassen ohne Spannung'],
    },
  },
  {
    slug: 'rudern-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=T3N-TO4reLQ',
    name: 'Rudern mit Langhantel (vorgebeugt)',
    category: 'compound',
    primaryMuscles: ['back_lats', 'back_rhomboids'],
    secondaryMuscles: ['biceps', 'shoulders_rear', 'lower_back'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    execution: {
      setup: 'Hüftbreiter Stand, Hüfte nach hinten, Oberkörper ca. 45° vorgebeugt, neutrale Wirbelsäule.',
      movement: 'Stange zum unteren Bauch ziehen, Ellbogen nach hinten, kurz halten, kontrolliert ab.',
      cues: ['Rücken bleibt neutral', 'Schulterblätter zusammen am Endpunkt'],
      commonMistakes: ['Rundrücken', 'Hochreißen mit Schwung'],
    },
  },
  {
    slug: 'rudern-kurzhantel-einarmig',
    videoUrl: 'https://www.youtube.com/watch?v=tLnlWj7LQ34',
    name: 'Einarmiges Kurzhantelrudern',
    category: 'compound',
    primaryMuscles: ['back_lats'],
    secondaryMuscles: ['back_rhomboids', 'biceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Bank: ein Knie + eine Hand auflegen, Rücken parallel, KH in der freien Hand.',
      movement: 'KH zur Hüfte ziehen, Ellbogen nach hinten oben, kurz halten, ab.',
      cues: ['Schulter unten', 'Rücken nicht rotieren'],
      commonMistakes: ['Schulter zuckt nach oben', 'Rotation des Oberkörpers'],
    },
  },
  {
    slug: 'rudern-kabel-eng',
    videoUrl: 'https://www.youtube.com/watch?v=XaHV_8Nbyug',
    name: 'Rudern am Kabel (enger Griff)',
    category: 'compound',
    primaryMuscles: ['back_lats', 'back_rhomboids'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Aufrechter Sitz, Beine leicht gebeugt, Brust raus.',
      movement: 'Griff zum Bauch ziehen, Ellbogen eng am Körper, langsam zurück.',
      cues: ['Schulterblätter aktivieren', 'Keine Hyperextension nach hinten'],
      commonMistakes: ['Mit dem ganzen Körper schwingen'],
    },
  },
  {
    slug: 'rudern-maschine',
    videoUrl: 'https://www.youtube.com/watch?v=FU6YQawma2Q',
    name: 'Rudern an der Maschine',
    category: 'compound',
    primaryMuscles: ['back_lats', 'back_rhomboids'],
    secondaryMuscles: ['biceps'],
    equipment: 'machine',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Brustpolster fest, Griffe in Schulterhöhe.',
      movement: 'Griffe Richtung Körper ziehen, Schulterblätter zusammen, langsam zurück.',
      cues: ['Sauberer ROM', 'Keine Schulterhochzieher'],
      commonMistakes: ['Zu schwer → Schwung'],
    },
  },
  {
    slug: 'kreuzheben',
    videoUrl: 'https://www.youtube.com/watch?v=GxsLrTzyGUU',
    name: 'Kreuzheben (konventionell)',
    category: 'compound',
    primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
    secondaryMuscles: ['back_lats', 'back_traps', 'quads', 'forearms'],
    equipment: 'barbell',
    defaultRestSeconds: 240,
    execution: {
      setup: 'Hüftbreiter Stand, Stange über Mittelfuß, schulterbreiter Griff, Schienbein an der Stange.',
      movement: 'Hüfte und Knie gleichzeitig strecken, Stange dicht am Körper, oben Hüfte voll strecken.',
      cues: ['Rücken neutral', 'Lats anspannen ("Orangen unter den Achseln zerquetschen")', 'Druck in den Boden'],
      commonMistakes: ['Rundrücken', 'Hyperextension oben', 'Stange weg vom Körper'],
    },
  },
  {
    slug: 'kreuzheben-rumaenisch',
    videoUrl: 'https://www.youtube.com/watch?v=uhghy9pFIPY',
    name: 'Kreuzheben rumänisch',
    category: 'compound',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    execution: {
      setup: 'Stange auf Hüfthöhe, schulterbreiter Stand, leichte Knie.',
      movement: 'Hüfte nach hinten, Stange entlang der Beine senken bis Stretch in Hamstrings, dann Hüfte vor.',
      cues: ['Hüfte führt die Bewegung', 'Knie nur leicht beugen', 'Stange dicht am Körper'],
      commonMistakes: ['Knie zu sehr beugen (wird zum normalen Kreuzheben)', 'Rundrücken'],
    },
  },
  {
    slug: 'hyperextensions',
    videoUrl: 'https://www.youtube.com/watch?v=qtjJUWCnDyE',
    name: 'Hyperextensions',
    category: 'isolation',
    primaryMuscles: ['lower_back', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
    execution: {
      setup: 'Hüfte auf Polster, Füße fest eingeklemmt.',
      movement: 'Oberkörper kontrolliert absenken, dann durch Glutes nach oben bis gerade Linie.',
      cues: ['Nicht überstrecken', 'Glutes aktiv'],
      commonMistakes: ['Hyperextension am Endpunkt'],
    },
  },

  // ───── Schultern ─────
  {
    slug: 'schulterdruecken-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=bMksDb5a3P0',
    name: 'Schulterdrücken Langhantel (stehend)',
    category: 'compound',
    primaryMuscles: ['shoulders_front'],
    secondaryMuscles: ['shoulders_side', 'triceps', 'abs'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    execution: {
      setup: 'Hüftbreiter Stand, Stange auf vorderen Schultern, Ellbogen leicht vor der Stange.',
      movement: 'Stange senkrecht über Kopf drücken, kurz Kopf nach vorne, oben volle Streckung.',
      cues: ['Bauch und Glutes fest (kein Hohlkreuz)', 'Stange senkrecht'],
      commonMistakes: ['Stange nach vorne drücken', 'Hyperextension Lendenwirbel'],
    },
  },
  {
    slug: 'schulterdruecken-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=1jYq9QQEWqE',
    name: 'Schulterdrücken Kurzhantel (sitzend)',
    category: 'compound',
    primaryMuscles: ['shoulders_front'],
    secondaryMuscles: ['shoulders_side', 'triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Aufrechte Bank, KHs auf Schulterhöhe, Handflächen nach vorne.',
      movement: 'KHs senkrecht nach oben drücken bis fast Berührung, dann kontrolliert ab.',
      cues: ['Ellbogen leicht vor der Schulter', 'Volle Streckung oben'],
      commonMistakes: ['KHs aneinander schlagen oben', 'Hohlkreuz'],
    },
  },
  {
    slug: 'arnold-press',
    videoUrl: 'https://www.youtube.com/watch?v=6Z15_WdXmVw',
    name: 'Arnold Press',
    category: 'compound',
    primaryMuscles: ['shoulders_front', 'shoulders_side'],
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Start mit KHs vor der Brust, Handflächen zum Körper.',
      movement: 'Hände während des Drückens rotieren bis am Endpunkt nach vorne zeigend.',
      cues: ['Saubere Rotation', 'Volle ROM'],
      commonMistakes: ['Zu schwer → Rotation leidet'],
    },
  },
  {
    slug: 'seitheben-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=Y29xKcze8Ik',
    name: 'Seitheben Kurzhantel',
    category: 'isolation',
    primaryMuscles: ['shoulders_side'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Aufrechter Stand, leichte Ellbogenbeugung, KHs an den Seiten.',
      movement: 'Arme seitlich anheben bis Schulterhöhe, kurz halten, langsam ab.',
      cues: ['Kleine Finger leicht höher als Daumen', 'Schultern nicht hochziehen'],
      commonMistakes: ['Mit Schwung arbeiten', 'Über Schulterhöhe heben'],
    },
  },
  {
    slug: 'seitheben-kabel',
    videoUrl: 'https://www.youtube.com/watch?v=qitQHqNZbeM',
    name: 'Seitheben am Kabel',
    category: 'isolation',
    primaryMuscles: ['shoulders_side'],
    secondaryMuscles: [],
    equipment: 'cable',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Seitlich zum Kabel stehen, Griff in der äußeren Hand.',
      movement: 'Arm zur Seite anheben bis Schulterhöhe, kontrolliert ab.',
      cues: ['Konstante Spannung über vollen ROM', 'Schulter unten'],
      commonMistakes: ['Körper nach außen lehnen für Schwung'],
    },
  },
  {
    slug: 'reverse-fly-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=JoCRRZ3zRtI',
    name: 'Reverse Fly Kurzhantel',
    category: 'isolation',
    primaryMuscles: ['shoulders_rear'],
    secondaryMuscles: ['back_rhomboids'],
    equipment: 'dumbbell',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Hüfte gebeugt, Rücken neutral, leichte Ellbogenbeugung.',
      movement: 'Arme nach hinten-oben heben, Schulterblätter zusammen, kontrolliert ab.',
      cues: [
        'Bewegung kommt aus den hinteren Schultern, nicht aus den Trapezius',
        'Schulterblätter erst am Endpunkt zusammen, nicht von Anfang an',
        'Daumen leicht nach unten zeigen für mehr Rear-Delt-Anspannung',
      ],
      commonMistakes: ['Trapezius übernimmt (Schultern hochziehen)', 'Mit Schwung arbeiten statt kontrolliert'],
    },
  },
  {
    slug: 'face-pulls',
    videoUrl: 'https://www.youtube.com/watch?v=0Po47vvj9g4',
    name: 'Face Pulls am Kabel',
    category: 'isolation',
    primaryMuscles: ['shoulders_rear'],
    secondaryMuscles: ['back_rhomboids', 'back_traps'],
    equipment: 'cable',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Seil auf Augenhöhe, beide Hände am Seil, leichte Rücklage.',
      movement: 'Seil zum Gesicht ziehen, Hände auseinander, Ellbogen hoch.',
      cues: ['Volle externe Rotation am Endpunkt', 'Schulterblätter zusammen'],
      commonMistakes: ['Ellbogen fallen lassen'],
    },
  },
  {
    slug: 'shrugs-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=KbsQ1E8Hg0o',
    name: 'Shrugs (Langhantel)',
    category: 'isolation',
    primaryMuscles: ['back_traps'],
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Aufrechter Stand, Stange schulterbreit greifen, Arme gestreckt.',
      movement: 'Schultern senkrecht nach oben ziehen, kurz halten, langsam ab.',
      cues: ['Reine vertikale Bewegung', 'Keine Rotation'],
      commonMistakes: ['Schultern kreisen lassen'],
    },
  },

  // ───── Beine ─────
  {
    slug: 'kniebeuge-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=SbgHegC6lEs',
    name: 'Kniebeuge (High-Bar)',
    category: 'compound',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs'],
    equipment: 'barbell',
    defaultRestSeconds: 240,
    execution: {
      setup: 'Stange auf den oberen Trapezius, hüftbreiter Stand, Zehen leicht nach außen.',
      movement: 'Hüfte und Knie gleichzeitig beugen bis Oberschenkel parallel oder tiefer, hochdrücken.',
      cues: ['Knie in Richtung Zehen', 'Brust raus, Rücken neutral', 'Druck durch die ganze Fußsohle'],
      commonMistakes: ['Knie kollabieren nach innen', 'Fersen heben', 'Butt wink'],
    },
  },
  {
    slug: 'front-squat',
    videoUrl: 'https://www.youtube.com/watch?v=wyDbagKS7Rg',
    name: 'Front Squat',
    category: 'compound',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'abs', 'lower_back'],
    equipment: 'barbell',
    defaultRestSeconds: 180,
    execution: {
      setup: 'Stange auf vorderen Schultern, Ellbogen hoch, Front-Rack-Position.',
      movement: 'Aufrecht absinken, tief gehen, mit den Quadrizeps hochdrücken.',
      cues: ['Oberkörper aufrecht halten', 'Ellbogen oben'],
      commonMistakes: ['Stange rutscht (Ellbogen fallen)', 'Vorbeugen'],
    },
  },
  {
    slug: 'beinpresse-45grad',
    videoUrl: 'https://www.youtube.com/watch?v=q4W4_VJbKW0',
    name: 'Beinpresse 45°',
    category: 'compound',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'machine',
    defaultRestSeconds: 150,
    execution: {
      setup: 'Sitz so einstellen, dass Knie in 90° kommen. Füße schulterbreit auf der Plattform.',
      movement: 'Beine kontrolliert beugen bis fast vollständig, dann pressen.',
      cues: ['Knie folgen den Zehen', 'Unteren Rücken an der Lehne lassen'],
      commonMistakes: ['Knie nach innen', 'Po hebt von der Lehne ("Butt Wink")'],
    },
  },
  {
    slug: 'ausfallschritte-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=_DLIS8SySzs',
    name: 'Ausfallschritte (Walking Lunges) Kurzhantel',
    category: 'compound',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    execution: {
      setup: 'KHs an den Seiten, aufrechter Oberkörper.',
      movement: 'Großer Schritt nach vorne, hinteres Knie fast zum Boden, vorderes Bein streckt sich.',
      cues: ['Vorderes Knie über dem Sprunggelenk', 'Oberkörper aufrecht'],
      commonMistakes: ['Schritt zu kurz → Knie über Zehe', 'Kippen zur Seite'],
    },
  },
  {
    slug: 'bulgarian-split-squat',
    videoUrl: 'https://www.youtube.com/watch?v=VPhhE6bBzZE',
    name: 'Bulgarian Split Squat',
    category: 'compound',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Hinterer Fuß auf Bank, vorderer Fuß ein großer Schritt nach vorne.',
      movement: 'Vorderes Knie über dem Knöchel halten, absinken bis hinteres Knie knapp über dem Boden.',
      cues: ['Druck auf der vorderen Ferse', 'Oberkörper leicht vorgeneigt für mehr Glutes'],
      commonMistakes: ['Hinterer Fuß zu nah', 'Knie über Zehe'],
    },
  },
  {
    slug: 'beinstrecker',
    videoUrl: 'https://www.youtube.com/watch?v=tTbJBUKnWU8',
    name: 'Beinstrecker',
    category: 'isolation',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: 'machine',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Polster auf Knöchelhöhe, Rücken fest an der Lehne.',
      movement: 'Beine bis fast voll strecken, kurz halten, langsam zurück.',
      cues: ['Volle Streckung oben', 'Volle Kontraktion 1 sek halten'],
      commonMistakes: ['Schwung holen', 'Knie ganz durchschnellen lassen'],
    },
  },
  {
    slug: 'beinbeuger-liegend',
    videoUrl: 'https://www.youtube.com/watch?v=P7-RxTVe6O0',
    name: 'Beinbeuger liegend',
    category: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: 'machine',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Bauchlage, Polster oberhalb der Ferse, Hüfte gegen das Polster drücken.',
      movement: 'Fersen Richtung Po ziehen, kurz halten, langsam zurück.',
      cues: ['Hüfte bleibt unten', 'Volle ROM'],
      commonMistakes: ['Hüfte hebt sich → Glutes übernehmen'],
    },
  },
  {
    slug: 'beinbeuger-sitzend',
    videoUrl: 'https://www.youtube.com/watch?v=Wy1SwoY2aaQ',
    name: 'Beinbeuger sitzend',
    category: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: 'machine',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Sitz einstellen, Rücken an der Lehne, Polster oberhalb der Ferse.',
      movement: 'Knie beugen bis Polster fast den Sitz berührt.',
      cues: ['Volle Streckung oben', 'Kontrollierte Negativ-Phase'],
      commonMistakes: ['Po vom Sitz heben'],
    },
  },
  {
    slug: 'hip-thrust',
    videoUrl: 'https://www.youtube.com/watch?v=S_uZP4UH6J0',
    name: 'Hip Thrust',
    category: 'compound',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    defaultRestSeconds: 120,
    execution: {
      setup: 'Schulterblätter auf Bank, Stange auf Hüfte (gepolstert), Füße flach.',
      movement: 'Hüfte nach oben drücken bis gerade Linie Knie-Hüfte-Schulter, oben Glutes maximal anspannen.',
      cues: ['Kinn auf Brust', 'Glutes 1 sek halten oben'],
      commonMistakes: ['Hyperextension Lendenwirbel oben', 'Knie kippen nach innen'],
    },
  },
  {
    slug: 'wadenheben-stehend',
    videoUrl: 'https://www.youtube.com/watch?v=SVtg-1loH4c',
    name: 'Wadenheben stehend',
    category: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'machine',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Schultern unter Polster, Ballen auf der Stufe, Fersen frei.',
      movement: 'So hoch wie möglich auf die Zehenspitzen, kurz halten, tief absenken.',
      cues: ['Volle ROM nach unten und oben', '1-2 sek Pause oben'],
      commonMistakes: ['Hopser/Schwung', 'Halbe ROM'],
    },
  },
  {
    slug: 'wadenheben-sitzend',
    videoUrl: 'https://www.youtube.com/watch?v=xz7sqxaJ-Ck',
    name: 'Wadenheben sitzend',
    category: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'machine',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Polster auf den Knien, Ballen auf der Stufe.',
      movement: 'Hoch auf die Ballen, kurz halten, langsam ab.',
      cues: ['Volle ROM', 'Soleus-fokussiert'],
      commonMistakes: ['Schwung mit den Knien'],
    },
  },

  // ───── Arme ─────
  {
    slug: 'bizeps-curls-langhantel',
    videoUrl: 'https://www.youtube.com/watch?v=QZEqB6wUPxQ',
    name: 'Bizepscurls Langhantel',
    category: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Aufrechter Stand, schulterbreiter Untergriff, Ellbogen an den Seiten.',
      movement: 'Stange Richtung Brust curlen, oben kurze Spannung, kontrolliert absenken.',
      cues: ['Ellbogen bewegen sich nicht nach vorne', 'Volle Streckung unten'],
      commonMistakes: ['Mit dem Oberkörper schwingen', 'Halbe ROM'],
    },
  },
  {
    slug: 'hammercurls-kurzhantel',
    videoUrl: 'https://www.youtube.com/watch?v=8XLxfXROrTo',
    name: 'Hammercurls Kurzhantel',
    category: 'isolation',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Aufrecht, KHs neutral (Daumen nach oben).',
      movement: 'KHs hochcurlen ohne Rotation, kurz halten, ab.',
      cues: ['Ellbogen fest am Körper', 'Daumen oben'],
      commonMistakes: ['Schultern zucken oben'],
    },
  },
  {
    slug: 'scott-curls',
    videoUrl: 'https://www.youtube.com/watch?v=OI6gZcAPUMU',
    name: 'Scott-Curls (Preacher Curl)',
    category: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: 'machine',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Oberarme fest auf das Polster, Sitz einstellen.',
      movement: 'Vollständig strecken unten, dann hoch curlen.',
      cues: ['Nie ganz ablegen', 'Volle ROM'],
      commonMistakes: ['Schwung holen', 'Sitz zu niedrig'],
    },
  },
  {
    slug: 'konzentrationscurls',
    videoUrl: 'https://www.youtube.com/watch?v=oPGBZHIxusU',
    name: 'Konzentrationscurls',
    category: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Auf Bank sitzen, Ellbogen am Oberschenkel innen.',
      movement: 'KH curlen mit voller Konzentration auf die Kontraktion.',
      cues: ['Volle Spannung im Bizeps', 'Kein Schwung'],
      commonMistakes: ['Mit dem Schultergelenk arbeiten'],
    },
  },
  {
    slug: 'trizepsdruecken-kabel',
    videoUrl: 'https://www.youtube.com/watch?v=_w-HpW70nSQ',
    name: 'Trizepsdrücken am Kabel',
    category: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'cable',
    defaultRestSeconds: 75,
    execution: {
      setup: 'Kabel hoch, Seil oder gerade Stange, Ellbogen am Körper.',
      movement: 'Unterarme nach unten strecken bis volle Streckung, langsam zurück.',
      cues: ['Ellbogen bleiben fix', 'Am Endpunkt 1 sek Spannung'],
      commonMistakes: ['Ellbogen wandern nach vorne', 'Oberkörper vorbeugen'],
    },
  },
  {
    slug: 'trizeps-french-press',
    videoUrl: 'https://www.youtube.com/watch?v=D47mYdoKllE',
    name: 'French Press (SZ-Stange)',
    category: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'barbell',
    defaultRestSeconds: 90,
    execution: {
      setup: 'Liegend auf Flachbank, Stange über der Stirn, Oberarme senkrecht.',
      movement: 'Stange Richtung Stirn senken, mit Trizeps wieder strecken.',
      cues: ['Oberarme nicht bewegen', 'Saubere ROM'],
      commonMistakes: ['Oberarme nach hinten kippen → wird zur Press'],
    },
  },
  {
    slug: 'enges-bankdruecken',
    videoUrl: 'https://www.youtube.com/watch?v=i1uIv77eo6I',
    name: 'Enges Bankdrücken',
    category: 'compound',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['shoulders_front'],
    equipment: 'barbell',
    defaultRestSeconds: 150,
    execution: {
      setup: 'Wie normales Bankdrücken, aber Griff schulterbreit.',
      movement: 'Stange senken, Ellbogen eng am Körper, hochdrücken.',
      cues: ['Ellbogen unter 45°', 'Sauberer ROM'],
      commonMistakes: ['Griff zu eng → Handgelenkstress'],
    },
  },
  {
    slug: 'trizeps-kickback',
    videoUrl: 'https://www.youtube.com/watch?v=6SS6K3lAwZ8',
    name: 'Trizeps Kickback Kurzhantel',
    category: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Oberkörper vorgebeugt, Oberarm parallel zum Boden, fixiert.',
      movement: 'Unterarm nach hinten strecken bis voll gestreckt.',
      cues: ['Oberarm bleibt fest', 'Volle Streckung'],
      commonMistakes: ['Oberarm zu niedrig', 'Mit Schwung arbeiten'],
    },
  },
  {
    slug: 'reverse-curls',
    videoUrl: 'https://www.youtube.com/watch?v=nRgxYX2Ve9w',
    name: 'Reverse Curls (Obergriff)',
    category: 'isolation',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Aufrechter Stand, Obergriff, schulterbreit.',
      movement: 'Stange Richtung Brust curlen, langsam ab.',
      cues: ['Handgelenke gerade', 'Volle ROM'],
      commonMistakes: ['Schwung'],
    },
  },

  // ───── Core ─────
  {
    slug: 'plank',
    videoUrl: 'https://www.youtube.com/watch?v=A2b2EmIg0dA',
    name: 'Plank',
    category: 'isolation',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lower_back'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Unterarmstütz, Ellbogen unter Schulter, Körper gerade Linie.',
      movement: 'Position halten, Bauch und Glutes aktiv anspannen.',
      cues: ['Hüfte nicht durchhängen lassen', 'Atmung locker'],
      commonMistakes: ['Hüfte zu hoch oder zu tief', 'Kopf hängt'],
    },
  },
  {
    slug: 'crunches',
    videoUrl: 'https://www.youtube.com/watch?v=GWIEON0VSaY',
    name: 'Crunches',
    category: 'isolation',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: 'bodyweight',
    defaultRestSeconds: 45,
    execution: {
      setup: 'Rückenlage, Knie gebeugt, Hände an den Schläfen oder vor der Brust.',
      movement: 'Oberkörper bis ca. 30° anheben, kurz halten, ab.',
      cues: ['Kinn weg vom Hals', 'Bewegung kommt aus dem Bauch'],
      commonMistakes: ['Am Nacken ziehen', 'Sit-up statt Crunch'],
    },
  },
  {
    slug: 'beinheben-haengend',
    videoUrl: 'https://www.youtube.com/watch?v=rbOJSK07AGA',
    name: 'Beinheben hängend',
    category: 'isolation',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: 'bodyweight',
    defaultRestSeconds: 75,
    execution: {
      setup: 'An Klimmzugstange hängen, Schultern aktiv.',
      movement: 'Beine kontrolliert hochheben (gestreckt oder gebeugt) bis 90° oder höher.',
      cues: ['Kein Schwung', 'Mit dem Becken kippen'],
      commonMistakes: ['Schaukeln', 'Halbe ROM'],
    },
  },
  {
    slug: 'kabel-crunches',
    videoUrl: 'https://www.youtube.com/watch?v=0KEP6A1deBE',
    name: 'Kabel-Crunches (knieend)',
    category: 'isolation',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: 'cable',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Knieend vor dem Kabelzug, Seil hinter dem Kopf.',
      movement: 'Oberkörper über die Bauchmuskeln nach unten beugen (zur Hüfte), kontrolliert zurück.',
      cues: ['Hüfte bleibt fix', 'Bauch krümmen, nicht Hüfte beugen'],
      commonMistakes: ['Mit der Hüfte arbeiten (wird zur Hüftbeugung)'],
    },
  },
  {
    slug: 'russian-twists',
    videoUrl: 'https://www.youtube.com/watch?v=JyUqwkVpsi8',
    name: 'Russian Twists',
    category: 'isolation',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lower_back'],
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
    execution: {
      setup: 'Sitzen, Knie angewinkelt, Oberkörper leicht zurückgelehnt.',
      movement: 'Oberkörper nach rechts und links rotieren, Bauch unter Spannung.',
      cues: ['Volle Rotation', 'Brust raus'],
      commonMistakes: ['Nur die Arme bewegen, Oberkörper bleibt steif'],
    },
  },
];

function buildExercise(t: SeedTemplate): Exercise {
  return {
    id: `seed-${t.slug}`,
    name: t.name,
    category: t.category,
    primaryMuscles: t.primaryMuscles,
    secondaryMuscles: t.secondaryMuscles,
    equipment: t.equipment,
    execution: t.execution,
    videoUrl: t.videoUrl,
    defaultRestSeconds: t.defaultRestSeconds,
    isCustom: false,
    createdAt: 0,
  };
}

export const SEED_EXERCISES: Exercise[] = TEMPLATES.map(buildExercise);

export const SEED_EXERCISE_COUNT = SEED_EXERCISES.length;
